// <auto-generated />
namespace Desafio2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cambio_precio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambio_precio));
        
        string IMigrationMetadata.Id
        {
            get { return "201910100205028_cambio_precio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
